caches:
  - name: apk_cache
    cache_key:
      - apk-cache
      - { agent: os }
      - { agent: arch }
    target_paths:
      - .apk-cache

  - name: node_modules
    cache_key:
      - node_modules
      - { agent: os }
      - { agent: arch }
      - { checksum: package-lock.json }
    target_paths:
      - node_modules
