steps:
  - label: "Hello World"
    command: echo "Hello, world!"

  - label: ":npm: Install"
    command:
      - "mkdir -p \"$(pwd)/.apk-cache\""
      - "echo '~~~ :package: Restoring apk cache'"
      - "buildkite-agent cache restore --names apk_cache --debug"
      - "echo '~~~ :alpine: Installing Node.js (apk)'"
      - "apk update --cache-dir \"$(pwd)/.apk-cache\""
      - "apk add --cache-dir \"$(pwd)/.apk-cache\" nodejs npm"
      - "echo '~~~ :package: Saving apk cache'"
      - "buildkite-agent cache save --names apk_cache --debug"
      - "echo '~~~ :package: Restoring node_modules cache'"
      - "buildkite-agent cache restore --names node_modules --debug"
      - "echo '+++ :npm: Installing dependencies'"
      - "npm install"
      - "echo '+++ :mag: Listing installed packages'"
      - "npm ls --all"
      - "echo '~~~ :package: Saving node_modules cache'"
      - "buildkite-agent cache save --names node_modules --debug"
